/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CaseMobileGallery = {
  _type: "caseMobileGallery";
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type CaseFullWidth = {
  _type: "caseFullWidth";
  videoUrl?: string;
};

export type CaseDevice = {
  _type: "caseDevice";
  videoUrl?: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  padBottom?: boolean;
};

export type CaseStudy = {
  _type: "caseStudy";
  services?: string;
  credits?: string;
  liveUrl?: string;
  cover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  stage?: string;
  blocks?: Array<{
    _key: string;
  } & CaseDevice | {
    _key: string;
  } & CaseFullWidth | {
    _key: string;
  } & CaseMobileGallery>;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  discipline?: string;
  country?: string;
  year?: string;
  thumb?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  tint?: string;
  order?: number;
  caseStudy?: CaseStudy;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = SanityImageAssetReference | CaseMobileGallery | CaseFullWidth | CaseDevice | CaseStudy | Project | SanityImageCrop | SanityImageHotspot | Slug | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../camcoder-folio/sanity/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project" && defined(slug.current)] | order(order asc) {      _id,  title,  "slug": slug.current,  discipline,  country,  year,  thumb,  tint  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  discipline: string | null;
  country: string | null;
  year: string | null;
  thumb: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  tint: string | null;
}>;

// Source: ../camcoder-folio/sanity/queries.ts
// Variable: PROJECT_LABELS_QUERY
// Query: *[_type == "project" && defined(slug.current)] | order(order asc) {    "slug": slug.current,    title  }
export type PROJECT_LABELS_QUERY_RESULT = Array<{
  slug: string | null;
  title: string | null;
}>;

// Source: ../camcoder-folio/sanity/queries.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)] { "slug": slug.current }
export type PROJECT_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../camcoder-folio/sanity/queries.ts
// Variable: PROJECT_TITLE_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] { title }
export type PROJECT_TITLE_QUERY_RESULT = {
  title: string | null;
} | null;

// Source: ../camcoder-folio/sanity/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {      _id,  title,  "slug": slug.current,  discipline,  country,  year,  thumb,  tint,    caseStudy {      services,      credits,      liveUrl,      cover,      logo,      stage,      blocks[] {        _key,        _type,        _type == "caseDevice" => { videoUrl, poster, padBottom },        _type == "caseFullWidth" => { videoUrl },        _type == "caseMobileGallery" => { images[] { _key, ... } }      }    }  }
export type PROJECT_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  discipline: string | null;
  country: string | null;
  year: string | null;
  thumb: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  tint: string | null;
  caseStudy: {
    services: string | null;
    credits: string | null;
    liveUrl: string | null;
    cover: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    logo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    stage: string | null;
    blocks: Array<{
      _key: string;
      _type: "caseDevice";
      videoUrl: string | null;
      poster: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      padBottom: boolean | null;
    } | {
      _key: string;
      _type: "caseFullWidth";
      videoUrl: string | null;
    } | {
      _key: string;
      _type: "caseMobileGallery";
      images: Array<{
        _key: string;
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      }> | null;
    }> | null;
  } | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"project\" && defined(slug.current)] | order(order asc) {\n    \n  _id,\n  title,\n  \"slug\": slug.current,\n  discipline,\n  country,\n  year,\n  thumb,\n  tint\n\n  }\n": PROJECTS_QUERY_RESULT;
    "\n  *[_type == \"project\" && defined(slug.current)] | order(order asc) {\n    \"slug\": slug.current,\n    title\n  }\n": PROJECT_LABELS_QUERY_RESULT;
    "\n  *[_type == \"project\" && defined(slug.current)] { \"slug\": slug.current }\n": PROJECT_SLUGS_QUERY_RESULT;
    "\n  *[_type == \"project\" && slug.current == $slug][0] { title }\n": PROJECT_TITLE_QUERY_RESULT;
    "\n  *[_type == \"project\" && slug.current == $slug][0] {\n    \n  _id,\n  title,\n  \"slug\": slug.current,\n  discipline,\n  country,\n  year,\n  thumb,\n  tint\n,\n    caseStudy {\n      services,\n      credits,\n      liveUrl,\n      cover,\n      logo,\n      stage,\n      blocks[] {\n        _key,\n        _type,\n        _type == \"caseDevice\" => { videoUrl, poster, padBottom },\n        _type == \"caseFullWidth\" => { videoUrl },\n        _type == \"caseMobileGallery\" => { images[] { _key, ... } }\n      }\n    }\n  }\n": PROJECT_QUERY_RESULT;
  }
}

